### ISSUE TITLE
use this repo with ur3e failed to fetch current robot state

### ISSUE THREAD

**Issue by Aruen24** [catmulti7/dual_ur_ros_2#4]
**use W/A/S/D/Q/E and I/J/K/L/U/O to control the robot**
[robot_control-2] control value0 -0.04 0
[robot_control-2] [INFO] [1730363510.242402376] [moveit_ros.current_state_monitor]: Listening to joint states on topic 'joint_states'
[robot_control-2] control value0.04 -0.04 0
[robot_control-2] control value0.04 -0 0
[robot_control-2] control value0 -0 0
[robot_control-2] [INFO] [1730363511.242537570] [moveit_ros.current_state_monitor]: Didn't receive robot state (joint angles) with recent timestamp within 1.000000 seconds. Requested time 1730363510.242439, but latest received state has time 0.000000.
[robot_control-2] Check clock synchronization if your are running ROS across multiple machines!
[robot_control-2] [ERROR] [1730363511.242596805] [move_group_interface]: Failed to fetch current robot state
[robot_control-2] current pose is0 0 0
[robot_control-2] goal pos 0 0 0
[robot_control-2] [INFO] [1730363512.242693899] [moveit_ros.current_state_monitor]: Didn't receive robot state (joint angles) with recent timestamp within 1.000000 seconds. Requested time 1730363511.242615, but latest received state has time 0.000000.
[robot_control-2] Check clock synchronization if your are running ROS across multiple machines!
[robot_control-2] [ERROR] [1730363512.242739923] [move_group_interface]: Failed to fetch current robot state
[robot_control-2] [INFO] [1730363513.242802216] [moveit_ros.current_state_monitor]: Didn't receive robot state (joint angles) with recent timestamp within 1.000000 seconds. Requested time 1730363512.242744, but latest received state has time 0.000000.
[robot_control-2] Check clock synchronization if your are running ROS across multiple machines!
[robot_control-2] [ERROR] [1730363513.242842439] [move_group_interface]: Failed to fetch current robot state
[ERROR] [robot_control-2]: process has died [pid 107885, exit code -11, cmd '/ROS2/IsaacSim-ros_workspaces/ur3e_ws/install/robot_control/lib/robot_control/robot_control --ros-args -r __node:=robot_control -r __ns:=/arm_0 --params-file /tmp/launch_params_p7ocvagv --params-file /tmp/launch_params_4h2qi_gy --params-file /ROS2/IsaacSim-ros_workspaces/ur3e_ws/install/dual_ur5_moveit_config/share/dual_ur5_moveit_config/config/kinematics.yaml --params-file /tmp/launch_params_6obpy0hz --params-file /tmp/launch_params_0nhphpo7'].

**Comment by catmulti7** [comment]
@Aruen24,
Can you check topic `/arm_0/joint_states` and `/arm_1/joint_states` to see if joints states have been published correctly?

**Comment by Aruen24** [comment]
> @Aruen24, Can you check topic `/arm_0/joint_states` and `/arm_1/joint_states` to see if joints states have been published correctly?

@catmulti7 ros2 topic echo /arm_0/joint_states
ros2 topic echo /arm_1/joint_states
no output

ros2 topic info /arm_0/joint_states
Publisher count: 0
Subscription count: 1

your dual_ur_control.launch.py 
#arm0_with_namespace
arm1_with_namespace
It's commented out, can't both be started at the same time?

**Comment by catmulti7** [comment]
@Aruen24 
> #arm0_with_namespace
> arm1_with_namespace


They can be started at the same time. Uncomment `arm0_with_namespace` and `arm_0_moveit_with_namespace` in `dual_ur_moveit_planning.launch.py`  

And both `/arm_0/joint_states` and `/arm_1/joint_states` got no output and 0 publisher? The problem seeems related to driver.

**Comment by Aruen24** [comment]
> @Aruen24
> 
> > #arm0_with_namespace
> > arm1_with_namespace
> 
> They can be started at the same time. Uncomment `arm0_with_namespace` and `arm_0_moveit_with_namespace` in `dual_ur_moveit_planning.launch.py`
> 
> And both `/arm_0/joint_states` and `/arm_1/joint_states` got no output and 0 publisher? The problem seeems related to driver.

@catmulti7 
 **arm_1_with_namespace = GroupAction(
     actions=[
         PushRosNamespace('arm_1'),
         arm_1
      ]
    )
If I release the above GroupAction code and run the dual_ur_control.launch.py, the following error will be reported**

[spawner-7] [ERROR] [1730441096.519024033] [arm_1.spawner_scaled_joint_trajectory_controller]: Controller manager not available
[spawner-8] [ERROR] [1730441096.521158570] [arm_1.spawner_joint_state_broadcaster]: Controller manager not available
[spawner-9] [ERROR] [1730441096.537168156] [arm_1.spawner_forward_position_controller]: Controller manager not available
[ERROR] [spawner-7]: process has died [pid 182340, exit code 1, cmd '/opt/ros/humble/lib/controller_manager/spawner scaled_joint_trajectory_controller -c /controller_manager --controller-manager-timeout 10 --ros-args -r __ns:=/arm_1'].
[ERROR] [spawner-8]: process has died [pid 182342, exit code 1, cmd '/opt/ros/humble/lib/controller_manager/spawner --controller-manager /controller_manager --controller-manager-timeout 10 joint_state_broadcaster io_and_status_controller speed_scaling_state_broadcaster force_torque_sensor_broadcaster ur_configuration_controller --ros-args -r __ns:=/arm_1'].
[ERROR] [spawner-9]: process has died [pid 182344, exit code 1, cmd '/opt/ros/humble/lib/controller_manager/spawner --controller-manager /controller_manager --controller-manager-timeout 10 --inactive forward_position_controller --ros-args -r __ns:=/arm_1'].

**Comment by catmulti7** [comment]
> > @Aruen24
> > > #arm0_with_namespace
> > > arm1_with_namespace
> > 
> > 
> > They can be started at the same time. Uncomment `arm0_with_namespace` and `arm_0_moveit_with_namespace` in `dual_ur_moveit_planning.launch.py`
> > And both `/arm_0/joint_states` and `/arm_1/joint_states` got no output and 0 publisher? The problem seeems related to driver.
> 
> @catmulti7 **arm_1_with_namespace = GroupAction( actions=[ PushRosNamespace('arm_1'), arm_1 ] ) If I release the above GroupAction code and run the dual_ur_control.launch.py, the following error will be reported**
> 
> [spawner-7] [ERROR] [1730441096.519024033] [arm_1.spawner_scaled_joint_trajectory_controller]: Controller manager not available [spawner-8] [ERROR] [1730441096.521158570] [arm_1.spawner_joint_state_broadcaster]: Controller manager not available [spawner-9] [ERROR] [1730441096.537168156] [arm_1.spawner_forward_position_controller]: Controller manager not available [ERROR] [spawner-7]: process has died [pid 182340, exit code 1, cmd '/opt/ros/humble/lib/controller_manager/spawner scaled_joint_trajectory_controller -c /controller_manager --controller-manager-timeout 10 --ros-args -r __ns:=/arm_1']. [ERROR] [spawner-8]: process has died [pid 182342, exit code 1, cmd '/opt/ros/humble/lib/controller_manager/spawner --controller-manager /controller_manager --controller-manager-timeout 10 joint_state_broadcaster io_and_status_controller speed_scaling_state_broadcaster force_torque_sensor_broadcaster ur_configuration_controller --ros-args -r __ns:=/arm_1']. [ERROR] [spawner-9]: process has died [pid 182344, exit code 1, cmd '/opt/ros/humble/lib/controller_manager/spawner --controller-manager /controller_manager --controller-manager-timeout 10 --inactive forward_position_controller --ros-args -r __ns:=/arm_1'].

There should be more error message before these messages.

**Comment by Aruen24** [comment]
> > > @Aruen24
> > > > #arm0_with_namespace
> > > > arm1_with_namespace
> > > 
> > > 
> > > They can be started at the same time. Uncomment `arm0_with_namespace` and `arm_0_moveit_with_namespace` in `dual_ur_moveit_planning.launch.py`
> > > And both `/arm_0/joint_states` and `/arm_1/joint_states` got no output and 0 publisher? The problem seeems related to driver.
> > 
> > 
> > @catmulti7 **arm_1_with_namespace = GroupAction( actions=[ PushRosNamespace('arm_1'), arm_1 ] ) If I release the above GroupAction code and run the dual_ur_control.launch.py, the following error will be reported**
> > [spawner-7] [ERROR] [1730441096.519024033] [arm_1.spawner_scaled_joint_trajectory_controller]: Controller manager not available [spawner-8] [ERROR] [1730441096.521158570] [arm_1.spawner_joint_state_broadcaster]: Controller manager not available [spawner-9] [ERROR] [1730441096.537168156] [arm_1.spawner_forward_position_controller]: Controller manager not available [ERROR] [spawner-7]: process has died [pid 182340, exit code 1, cmd '/opt/ros/humble/lib/controller_manager/spawner scaled_joint_trajectory_controller -c /controller_manager --controller-manager-timeout 10 --ros-args -r __ns:=/arm_1']. [ERROR] [spawner-8]: process has died [pid 182342, exit code 1, cmd '/opt/ros/humble/lib/controller_manager/spawner --controller-manager /controller_manager --controller-manager-timeout 10 joint_state_broadcaster io_and_status_controller speed_scaling_state_broadcaster force_torque_sensor_broadcaster ur_configuration_controller --ros-args -r __ns:=/arm_1']. [ERROR] [spawner-9]: process has died [pid 182344, exit code 1, cmd '/opt/ros/humble/lib/controller_manager/spawner --controller-manager /controller_manager --controller-manager-timeout 10 --inactive forward_position_controller --ros-args -r __ns:=/arm_1'].
> 
> There should be more error message before these messages.

The problem has solved
